import type { Metadata } from "next";
import "./styles/globals.css";
import {LoadingProvider} from "@/components/layout/LoadingProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
      >
      <LoadingProvider>
        {children}
      </LoadingProvider>
      </body>
    </html>
  );
}
